version: '3.9'

services:

  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: a123456789
      MYSQL_DATABASE: demo
    volumes:
      - ./data:/docker-entrypoint-initdb.d
